import os
from pathlib import Path
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from .math_engine import AnalysisResultSchema

BASE_DIR = Path(__file__).resolve().parent.parent.parent 
FONT_PATH = os.path.join(BASE_DIR, "static", "fonts", "Arial.ttf") 
pdfmetrics.registerFont(TTFont('Arial', FONT_PATH))

class PDFGenerator:
    @staticmethod
    def generate_report(organization: str, period: str, data: AnalysisResultSchema) -> BytesIO:
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        if os.path.exists(FONT_PATH):
            pdfmetrics.registerFont(TTFont('Arial', FONT_PATH))
        else:
            print(f"Font not found at {FONT_PATH}, utilizing default.")

        # Заголовок
        p.drawString(50, height - 50, f"Financial Analysis Report")
        p.setFont("Helvetica", 12)
        p.drawString(50, height - 70, f"Org: {organization}")
        p.drawString(50, height - 85, f"Period: {period}")

        y = height - 120

        def draw_section(title, items):
            nonlocal y
            p.setFont("Helvetica-Bold", 12)
            p.drawString(50, y, title)
            y -= 20
            p.setFont("Helvetica", 10)
            for key, value in items.items():

                clean_key = key.replace("_", " ").title()

                if isinstance(value, float):
                    text = f"{clean_key}: {value:.2f}"
                else:
                    text = f"{clean_key}: {value}"
                
                p.drawString(70, y, text)
                y -= 15
            y -= 10 


        draw_section("Liquidity Analysis", data.liquidity)
        draw_section("Profitability Analysis (%)", data.profitability)
        draw_section("Business Activity", data.activity)
        draw_section("Bankruptcy (Altman Model)", data.bankruptcy_altman)
        draw_section("Bankruptcy (Taffler Model)", data.bankruptcy_taffler)


        p.setFont("Helvetica-Oblique", 8)
        p.drawString(50, 30, "Generated by Enterprise Analysis Service")
        
        p.showPage()
        p.save()
        
        buffer.seek(0)
        return buffer
