import os
from pathlib import Path
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont


CURRENT_DIR = Path(__file__).resolve().parent
APP_DIR = CURRENT_DIR.parent 
FONT_PATH = os.path.join(APP_DIR, "static", "fonts", "arialmt.ttf")

try:
    if os.path.exists(FONT_PATH):
        pdfmetrics.registerFont(TTFont('Arial', FONT_PATH))
        DEFAULT_FONT = 'Arial'
        BOLD_FONT = 'Arial' 
    else:
        print(f"Warning: Font not found at {FONT_PATH}. Using Helvetica.")
        DEFAULT_FONT = 'Helvetica'
        BOLD_FONT = 'Helvetica-Bold'
except Exception as e:
    print(f"Error registering font: {e}")
    DEFAULT_FONT = 'Helvetica'
    BOLD_FONT = 'Helvetica-Bold'

class PDFGenerator:
    @staticmethod
    def generate_report(organization: str, period: str, data) -> BytesIO:
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        p.setFont(BOLD_FONT, 16)
        p.drawString(50, height - 50, f"Financial Analysis Report")
        
        p.setFont(DEFAULT_FONT, 12)
        p.drawString(50, height - 70, f"Org: {organization}")
        p.drawString(50, height - 85, f"Period: {period}")

        y = height - 120

        def draw_section(title, items):
            nonlocal y
            if y < 50:
                p.showPage()
                y = height - 50
                p.setFont(DEFAULT_FONT, 12)

            p.setFont(BOLD_FONT, 12)
            p.drawString(50, y, title)
            y -= 20
            p.setFont(DEFAULT_FONT, 10)
            
            iterator = items.model_dump().items() if hasattr(items, 'model_dump') else items.items()

            for key, value in iterator:
                clean_key = key.replace("_", " ").title()
                
                if isinstance(value, float):
                    text = f"{clean_key}: {value:.2f}"
                else:
                    text = f"{clean_key}: {value}"
                
                p.drawString(70, y, text)
                y -= 15
            y -= 10 

        if data.liquidity:
            draw_section("Liquidity Analysis", data.liquidity)
        if data.profitability:
            draw_section("Profitability Analysis (%)", data.profitability)
        if data.activity:
            draw_section("Business Activity", data.activity)
        if data.bankruptcy_altman:
            draw_section("Bankruptcy (Altman Model)", data.bankruptcy_altman)
        if data.bankruptcy_taffler:
            draw_section("Bankruptcy (Taffler Model)", data.bankruptcy_taffler)

        p.setFont(DEFAULT_FONT, 8)
        p.drawString(50, 30, "Generated by Enterprise Analysis Service")
        
        p.showPage()
        p.save()
        
        buffer.seek(0)
        return buffer
